version: "2"
volumes:
  db_data:
    driver: local
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db_data:/var/lib/postgresql/data
  server:
    build: .
    command: npm run start:prod
    expose:
      - 3001
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - APP_PORT=3001
      - APP_LOG_PATH=/opt/administration-backend.log
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=gas-ps-integration
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - ELASTICSEARCH_HOST=http://172.29.30.75
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_USERNAME=grub
      - ELASTICSEARCH_PASSWORD=hb1k5rW4
      - KAFKA_HOST=172.29.30.57
      - KAFKA_PORT=9092
      - NSI_DICTIONARY_URL=https://gasps-dev.gost-group.com/nsi
      - NSI_DICTIONARY_LOGIN=gasps
      - NSI_DICTIONARY_PASSWORD=Hfcjhn9C4n7VcHE6
      - NSI_DICTIONARY_DATA_HEAP_SIZE=500
      - DIB_URL=https://gasps-dev.gost-group.com
      - MINIO_END_POINT=172.29.30.58
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=integration-5Msk1V3xfaWzHtBsMnlCQ
      - MINIO_SECRET_KEY=LXvCIGdjUgvd6pLmbFEm9bmjqpHjThAAnPlSrzt3L8
      - MINIO_BUCKET=integration
    links:
      - db
